# Agent single objective sweeper
# Get conf by running --cfg job --resolve

# State selector choices, env/datasource/state_selector:
# df_fullrandom - Choix David D avec HSLinUCB mais pb. singular matrix avec KFOO
# df_randombuffer 
# df_sequential - At each reset choose the workload from the current episode index, go to the top or bottom state of the workload as specified by topdown argument.
# df_fullsequential - Choix PR, Optmal? - Start at the begining of the dataset and go to the next state at each reset. When bottom state is reached, next reset will go to the next workload (auto rewind)
# df_topdownrocker - Especially for tests Start sequentialy each workload twice. First from Top, second from Bottom
# df_randomtopdown - Starts randomly at each Reset from Top buffer value or Bottom buffer value
# db_live - Connected to a live database, at each reset do not touch the buffer value

# All agents:
# linucb_kfoo (LinUCB)
# linucb_hs   (HSLinUCB, i.e. HorizontalScaling LinUCB)
# ppo
# dqn
# a2c
# sac
# ddpg

# python run_agent.py --cfg job agent/env/state_selector@agent.env.state_selector_train=df_topdownrocker

defaults:
  - base  # ouput paths, verbosity, ...
  - db: tun06
  - workload/base
  - tuner: a2c
  - override tuner/env/state_selector@tuner.env.state_selector_test: db_live
  - override tuner/reward: db_live
#  - override /hydra/launcher: joblib
  - _self_

# Defines model to load and use to tune the database
#version_minor: 56_dqn_alphabeta_sweepseed
version_minor: 56_a2c_alphabeta_sweepseed # => E11_56_a2c_alphabeta_sweepseed_disq
live_iterations_name: agent-T7S0

#db:
#  warmups:
#    on_start: 50        # This value is badly used for bith episodes and tests. Not ideal, should be fixed. Wait time at each new episode and new step
#    on_buf_update: 30  # NOT USED - hard coded with db_warmup_time below
tuner:
  TEST_EPISODES_COUNT: 1
  TEST_STEPS_PER_EPISODE: null  # Never stop the first episode, eq. to numpy.inf
  env:
    state_selector_train: null  # Do not use any state selector for training. Training is out of scope
    state_selector_test:
      buf_reset_policy: stay # stay, min, mean, max, ...


DETERMINISTIC: False  # Flag passed to SB3's predict method. Default is False
verbosity: 1

# Should not be touched
#trial: 0
#seed: 0
eval_data: False     # Use EVAL dataset or TEST dataset
pickles_dirname: E${version}_${version_minor}
pickles_path: ${output_path}/${pickles_dirname}_disq

