# Get conf by running --cfg job --resolve

# python run_dbsas_xxx.py --cfg job 

defaults:
  - base  # ouput paths, verbosity, ...
  - datasets@orig: traintest-dbsas
  - datasets@dbsas: traintest-dbsas
  - _self_

datasets_prefix: workloads
#version: 13 # Digital Twin dataset
#version_minor: 3

# Input datasets files with .pickles extension, for original and dbsas datasets
dataset_orig_import_file: original_dataset
dataset_dbsas_import_file: db_fullnetwork_generated_full_dataset_discrete

# Output pickles files prefixes for original and dbsas datasets
orig:
  pickles_prefix: ${datasets_prefix}_orig

dbsas:
  pickles_prefix: ${datasets_prefix}_dbsas