# Get conf by running --cfg job --resolve

# python run_simu_xxx.py --cfg job 

defaults:
  - base  # ouput paths, verbosity, ...
  - datasets@orig: traintest-full     # Use same selecctor as default one in run_agentxxx....
  - datasets@dbsas: traintest-full    # Use same selecctor as default one in run_agentxxx
  - datasets@cvae: traintest-full     # Use same selecctor as default one in run_agentxxx
  - datasets@tabddpm: traintest-full  # Use same selecctor as default one in run_agentxxx
  - _self_

# objective_margin is used by Basic baseline in particular to apply a margin factor on the SLA threshold, 
# Basic baseline choose to do UP arm if the current latency is over the SLA latency threshold (ex. 20ms).
# objective_margin defines an area under the SLA threshold into Basic BL decide to stop to decrease the buffer and choose to STAY at the current buffer value.
# Ex if SLA threshold is 20ms and objective_margin=0.3, then the STAY zone is between 17ms and 20ms, meaning that if LAT is <17ms, Basic BL select a DOWN arm
# Ex if SLA threshold is 20ms and objective_margin=0.1, then the STAY zone is between 19ms and 20ms, meaning that if LAT is <19ms, Basic BL select a DOWN arm 
objective_margin: 0.3

# Input datasets files with .pickles extension. The "Original" one is issued from real observation samples (DataRef), the others are generated/simulated ones 
# ORIGinal dataset
dataset_orig_import_file: import/workloads_fe_11  # Original, NOT simulated data from real observations
orig:
  pickles_prefix: ${datasets_prefix}_orig

# DBSAS generated dataset
dataset_dbsas_import_file: !!null  # DBSAS generated dataset 
dbsas:
  pickles_prefix: ${datasets_prefix}_dbsas

# CVAE generated dataset
dataset_cvae_import_file: !!null  # CVAE generated dataset
cvae:
  pickles_prefix: ${datasets_prefix}_cvae

# TABDDPM generated dataset
dataset_tabddpm_import_file: !!null # TABDDPM generated dataset
tabddpm:
  pickles_prefix: ${datasets_prefix}_tabddpm
