# Get conf by running --cfg job --resolve


# What will happen if a agent is only able to use STAY arm => what will be its performance ??
# python run_simple_stay_test.py

defaults:
  - base  # ouput paths, verbosity, ...
  - workload/base
  - datasets: traintest-full
  - tuner: stay
  - _self_

tuner:
  env:
    state_selector_test:
      fixed_percents: 0.5

version_minor: 56_simple_stay_test
trial: 1
seed: 0
eval_data: False     # Use EVAL dataset or TEST dataset

verbosity: 1
pickles_dirname: E${version}_${version_minor}
pickles_path: ${output_path}/${pickles_dirname}


