
defaults:
  - warmups: sigma # Sigma method checking the measure server's stability and expect reduced wait time at each step
  - cache: 8GB
  - variables: mariadb
 
host: localhost
port: 3306
user: root
password: adbms
database: adbms
